#include "game/content/content_json.h"
#include "engine/data/json.h"
#include <charconv>
#include <limits>

namespace underworld::game::content {
namespace {
using engine::data::JsonArray; using engine::data::JsonObject; using engine::data::JsonNumber; using engine::data::JsonValue;
struct Ctx { std::vector<ContentJsonDiagnostic> d; void error(const JsonValue& v,std::string path,std::string msg){d.push_back({v.span.begin.line,v.span.begin.column,std::move(path),std::move(msg)});} void error(const JsonObject& o,std::string path,std::string msg){(void)o;d.push_back({1,1,std::move(path),std::move(msg)});} };
const JsonValue* field(const JsonObject& o,std::string_view n){for(auto& x:o)if(x.first==n)return &x.second;return nullptr;}
bool object(const JsonValue& v,std::string_view path,Ctx& c,const JsonObject*& o){o=std::get_if<JsonObject>(&v.value);if(!o){c.error(v,std::string(path),"must be an object");return false;}return true;}
bool fields(const JsonObject& o,std::initializer_list<std::string_view> a,std::string_view path,Ctx& c){for(auto& x:o){bool ok=false;for(auto n:a)ok|=x.first==n;if(!ok)c.error(x.second,std::string(path)+"."+x.first,"unknown field");}return true;}
const JsonValue* req(const JsonObject& o,std::string_view n,std::string_view path,Ctx& c){auto* v=field(o,n);if(!v)c.error(o,std::string(path)+"."+std::string(n),"missing required field");return v;}
bool str(const JsonValue& v,std::string_view path,Ctx& c,std::string& out){if(auto p=std::get_if<std::string>(&v.value)){out=*p;return true;}c.error(v,std::string(path),"must be a string");return false;}
bool u64(const JsonValue& v,std::string_view path,Ctx& c,std::uint64_t& out){auto n=std::get_if<JsonNumber>(&v.value);if(!n){c.error(v,std::string(path),"must be an unsigned integer");return false;}auto [p,e]=std::from_chars(n->lexeme.data(),n->lexeme.data()+n->lexeme.size(),out);if(e!=std::errc{}||p!=n->lexeme.data()+n->lexeme.size()){c.error(v,std::string(path),"outside unsigned integer range");return false;}return true;}
bool i64(const JsonValue& v,std::string_view path,Ctx& c,std::int64_t& out){auto n=std::get_if<JsonNumber>(&v.value);if(!n){c.error(v,std::string(path),"must be a signed integer");return false;}auto [p,e]=std::from_chars(n->lexeme.data(),n->lexeme.data()+n->lexeme.size(),out);if(e!=std::errc{}||p!=n->lexeme.data()+n->lexeme.size()){c.error(v,std::string(path),"outside signed integer range");return false;}return true;}
template<class T> bool ui(const JsonObject& o,std::string_view n,std::string_view path,Ctx& c,T& out){auto* v=req(o,n,path,c);if(!v)return false;std::uint64_t x{};if(!u64(*v,std::string(path)+"."+std::string(n),c,x)||x>std::numeric_limits<T>::max()){if(v)c.error(*v,std::string(path)+"."+std::string(n),"outside field range");return false;}out=static_cast<T>(x);return true;}
template<class T> bool si(const JsonObject& o,std::string_view n,std::string_view path,Ctx& c,T& out){auto* v=req(o,n,path,c);if(!v)return false;std::int64_t x{};if(!i64(*v,std::string(path)+"."+std::string(n),c,x)||x<std::numeric_limits<T>::min()||x>std::numeric_limits<T>::max()){if(v)c.error(*v,std::string(path)+"."+std::string(n),"outside field range");return false;}out=static_cast<T>(x);return true;}
bool idf(const JsonObject&o,std::string_view n,std::string_view path,Ctx&c,simulation::DefinitionId& out){std::string s;auto*v=req(o,n,path,c);return v&&str(*v,std::string(path)+"."+std::string(n),c,s)?(out=simulation::DefinitionId{s},true):false;}
template<class E> bool en(const JsonValue&v,std::string_view path,Ctx&c,std::string_view name,E& out);
template<> bool en(const JsonValue&v,std::string_view p,Ctx&c,std::string_view,gameplay::ItemCategory&x){std::string s;if(!str(v,p,c,s))return false;if(s=="consumable")x=gameplay::ItemCategory::consumable;else if(s=="equipment")x=gameplay::ItemCategory::equipment;else if(s=="key")x=gameplay::ItemCategory::key;else if(s=="misc")x=gameplay::ItemCategory::misc;else{c.error(v,std::string(p),"unknown ItemCategory");return false;}return true;}
template<> bool en(const JsonValue&v,std::string_view p,Ctx&c,std::string_view,AuthoredEquipmentSlot&x){std::string s;if(!str(v,p,c,s))return false;if(s=="armor")x=AuthoredEquipmentSlot::armor;else if(s=="accessory")x=AuthoredEquipmentSlot::accessory;else{c.error(v,std::string(p),"unknown equipment slot");return false;}return true;}
template<> bool en(const JsonValue&v,std::string_view p,Ctx&c,std::string_view,AuthoringCategory&x){std::string s;if(!str(v,p,c,s))return false;const std::pair<std::string_view,AuthoringCategory>a[]={{"enemy",AuthoringCategory::enemy},{"object",AuthoringCategory::object},{"pickup",AuthoringCategory::pickup},{"npc",AuthoringCategory::npc},{"item",AuthoringCategory::item},{"rewardProfile",AuthoringCategory::rewardProfile},{"rewardGrant",AuthoringCategory::rewardGrant},{"shop",AuthoringCategory::shop}};for(auto [n,e]:a)if(s==n){x=e;return true;}c.error(v,std::string(p),"unknown AuthoringCategory");return false;}
bool textArray(const JsonValue&v,std::string path,Ctx&c,std::vector<std::string>&out){auto*a=std::get_if<JsonArray>(&v.value);if(!a){c.error(v,path,"must be an array");return false;}for(size_t i=0;i<a->size();++i){std::string s;if(str((*a)[i],path+"["+std::to_string(i)+"]",c,s))out.push_back(std::move(s));}return true;}
bool itemDecode(const JsonValue&v,std::string path,Ctx&c,AuthoredItem&x){const JsonObject*o;if(!object(v,path,c,o))return false;fields(*o,{"id","visualId","category","stackLimit","use","equipment"},path,c);std::string s;std::uint32_t lim{};if(!idf(*o,"id",path,c,x.id)||!idf(*o,"visualId",path,c,x.visualId)||!(field(*o,"category")&&en(*field(*o,"category"),path+".category",c,"",x.category))||!ui(*o,"stackLimit",path,c,lim))return false;x.stackLimit=lim;if(auto*z=field(*o,"use");z&&!std::holds_alternative<std::nullptr_t>(z->value)){const JsonObject*u;if(!object(*z,path+".use",c,u))return false;fields(*u,{"kind","amount"},path+".use",c);std::string k;std::int64_t amount{};if(!str(*req(*u,"kind",path+".use",c),path+".use.kind",c,k)||k!="restoreHealth"||!si(*u,"amount",path+".use",c,amount))return false;x.use=gameplay::ItemUseDefinition{gameplay::ItemUseKind::restoreHealth,static_cast<int>(amount)};}if(auto*z=field(*o,"equipment");z&&!std::holds_alternative<std::nullptr_t>(z->value)){const JsonObject*e;if(!object(*z,path+".equipment",c,e))return false;fields(*e,{"slot","modifiers"},path+".equipment",c);AuthoredEquipment q;if(!en(*req(*e,"slot",path+".equipment",c),path+".equipment.slot",c,"",q.slot))return false;const JsonObject*m;auto*mv=req(*e,"modifiers",path+".equipment",c);if(!mv||!object(*mv,path+".equipment.modifiers",c,m))return false;fields(*m,{"maximumHealthBonus","playerAttackDamageBonus"},path+".equipment.modifiers",c);si(*m,"maximumHealthBonus",path+".equipment.modifiers",c,q.modifiers.maximumHealthBonus);si(*m,"playerAttackDamageBonus",path+".equipment.modifiers",c,q.modifiers.playerAttackDamageBonus);x.equipment=q;}return true;}
bool shopDecode(const JsonValue&v,std::string path,Ctx&c,AuthoredShop&x){const JsonObject*o;if(!object(v,path,c,o))return false;fields(*o,{"id","offers"},path,c);if(!idf(*o,"id",path,c,x.id))return false;const auto*av=req(*o,"offers",path,c);if(!av)return false;auto*arr=std::get_if<JsonArray>(&av->value);if(!arr){c.error(*av,path+".offers","must be an array");return false;}for(size_t i=0;i<arr->size();++i){const JsonObject*q;if(!object((*arr)[i],path+".offers["+std::to_string(i)+"]",c,q))continue;std::string pp=path+".offers["+std::to_string(i)+"]";fields(*q,{"itemId","playerBuyPrice","playerSellPrice"},pp,c);AuthoredShopOffer z;if(!idf(*q,"itemId",pp,c,z.itemId))continue;for(auto n:{"playerBuyPrice","playerSellPrice"})if(auto*t=field(*q,n)){if(std::holds_alternative<std::nullptr_t>(t->value))continue;std::uint64_t value{};if(u64(*t,pp+"."+n,c,value)){if(std::string_view(n)=="playerBuyPrice")z.playerBuyPrice=value;else z.playerSellPrice=value;}}x.offers.push_back(std::move(z));}return true;}
}

ContentJsonDecodeResult decodeAuthoredContentJson(std::string_view text){ContentJsonDecodeResult r;auto parsed=engine::data::parseJson(text);for(auto&d:parsed.diagnostics)r.diagnostics.push_back({d.location.line,d.location.column,{},d.message});if(!parsed.value)return r;const auto*root=std::get_if<JsonObject>(&parsed.value->value);if(!root){r.diagnostics.push_back({1,1,{},"top-level JSON value must be an object"});return r;}Ctx c;auto*f=field(*root,"format");auto*v=field(*root,"version");std::string fs;std::uint64_t ver{};if(!f||!str(*f,"format",c,fs)||fs!="dungeon-underworld-content")c.error(*parsed.value,"format","invalid format");if(!v||!u64(*v,"version",c,ver)||ver!=1)c.error(*parsed.value,"version","unsupported schema version");static const char*known[]={"format","version","tilesets","projectiles","attacks","behaviors","enemies","items","objects","pickups","npcVisuals","npcs","dialogues","quests","playerProgressions","rewardProfiles","rewardGrants","shops","authoringDescriptors","tileSemantics","stamps"};for(auto&m:*root){bool ok=false;for(auto n:known)ok|=m.first==n;if(!ok)c.error(m.second,m.first,"unknown top-level field");}
AuthoredContentPack out;auto cat=[&](const char*n)->const JsonArray*{auto*x=field(*root,n);if(!x)return nullptr;auto*a=std::get_if<JsonArray>(&x->value);if(!a)c.error(*x,n,"category must be an array");return a;};if(auto a=cat("tilesets"))for(size_t i=0;i<a->size();++i){const JsonObject*o;if(!object((*a)[i],"tilesets["+std::to_string(i)+"]",c,o))continue;std::string q;AuthoredTileset x;auto pth="tilesets["+std::to_string(i)+"]";idf(*o,"id",pth,c,x.id);if(auto*z=req(*o,"displayName",pth,c))str(*z,pth+".displayName",c,x.displayName);if(auto*z=req(*o,"relativeAssetPath",pth,c))str(*z,pth+".relativeAssetPath",c,x.relativeAssetPath);ui(*o,"tileSize",pth,c,x.tileSize);ui(*o,"columns",pth,c,x.columns);ui(*o,"rows",pth,c,x.rows);fields(*o,{"id","displayName","relativeAssetPath","tileSize","columns","rows"},pth,c);out.tilesets.push_back(std::move(x));}
if(auto a=cat("behaviors"))for(size_t i=0;i<a->size();++i){const JsonObject*o;if(!object((*a)[i],"behaviors",c,o))continue;AuthoredBehaviorProfile x;auto pth="behaviors["+std::to_string(i)+"]";idf(*o,"id",pth,c,x.id);si(*o,"detectionRangePixels",pth,c,x.detectionRangePixels);si(*o,"disengageRangePixels",pth,c,x.disengageRangePixels);ui(*o,"idleDurationTicks",pth,c,x.idleDurationTicks);ui(*o,"wanderDurationTicks",pth,c,x.wanderDurationTicks);fields(*o,{"id","detectionRangePixels","disengageRangePixels","idleDurationTicks","wanderDurationTicks"},pth,c);out.behaviors.push_back(std::move(x));}
if(auto a=cat("items"))for(size_t i=0;i<a->size();++i){AuthoredItem x;if(itemDecode((*a)[i],"items["+std::to_string(i)+"]",c,x))out.items.push_back(std::move(x));}
if(auto a=cat("shops"))for(size_t i=0;i<a->size();++i){AuthoredShop x;if(shopDecode((*a)[i],"shops["+std::to_string(i)+"]",c,x))out.shops.push_back(std::move(x));}
if(auto a=cat("authoringDescriptors"))for(size_t i=0;i<a->size();++i){const JsonObject*o;if(!object((*a)[i],"authoringDescriptors",c,o))continue;AuthoringDescriptor x;auto pth="authoringDescriptors["+std::to_string(i)+"]";idf(*o,"definitionId",pth,c,x.definitionId);if(auto*z=req(*o,"displayName",pth,c))str(*z,pth+".displayName",c,x.displayName);if(auto*z=req(*o,"category",pth,c))en(*z,pth+".category",c,"",x.category);if(auto*z=req(*o,"tags",pth,c))textArray(*z,pth+".tags",c,x.tags);fields(*o,{"definitionId","displayName","category","tags"},pth,c);out.authoringDescriptors.push_back(std::move(x));}
if(auto a=cat("playerProgressions"))for(size_t i=0;i<a->size();++i){const JsonObject*o;if(!object((*a)[i],"playerProgressions",c,o))continue;AuthoredPlayerProgression x;auto pth="playerProgressions["+std::to_string(i)+"]";idf(*o,"id",pth,c,x.id);auto*b=req(*o,"baseStats",pth,c);const JsonObject*bo;if(b&&object(*b,pth+".baseStats",c,bo)){fields(*bo,{"maximumHealth"},pth+".baseStats",c);si(*bo,"maximumHealth",pth+".baseStats",c,x.baseStats.maximumHealth);}auto*t=req(*o,"cumulativeExperienceThresholds",pth,c);if(t){auto*ar=std::get_if<JsonArray>(&t->value);if(!ar)c.error(*t,pth+".cumulativeExperienceThresholds","must be an array");else for(size_t j=0;j<ar->size();++j){std::uint64_t n{};if(u64((*ar)[j],pth+".cumulativeExperienceThresholds["+std::to_string(j)+"]",c,n))x.cumulativeExperienceThresholds.push_back(n);}}fields(*o,{"id","baseStats","cumulativeExperienceThresholds"},pth,c);out.playerProgressions.push_back(std::move(x));}
if(auto a=cat("rewardProfiles")){for(size_t i=0;i<a->size();++i){const JsonObject*o;if(!object((*a)[i],"rewardProfiles",c,o))continue;AuthoredRewardProfile x;auto pth="rewardProfiles["+std::to_string(i)+"]";idf(*o,"id",pth,c,x.id);ui(*o,"experience",pth,c,x.experience);auto*l=req(*o,"loot",pth,c);if(l){if(auto*ar=std::get_if<JsonArray>(&l->value)){for(size_t j=0;j<ar->size();++j){const JsonObject*q;if(!object((*ar)[j],pth+".loot["+std::to_string(j)+"]",c,q))continue;AuthoredLootEntry z;auto pp=pth+".loot["+std::to_string(j)+"]";idf(*q,"pickupDefinitionId",pp,c,z.pickupDefinitionId);ui(*q,"chanceBasisPoints",pp,c,z.chanceBasisPoints);ui(*q,"minimumCount",pp,c,z.minimumCount);ui(*q,"maximumCount",pp,c,z.maximumCount);fields(*q,{"pickupDefinitionId","chanceBasisPoints","minimumCount","maximumCount"},pp,c);x.loot.push_back(z);}}else c.error(*l,pth+".loot","must be an array");}fields(*o,{"id","experience","loot"},pth,c);out.rewardProfiles.push_back(std::move(x));}}
if(auto a=cat("rewardGrants")){for(size_t i=0;i<a->size();++i){const JsonObject*o;if(!object((*a)[i],"rewardGrants",c,o))continue;AuthoredRewardGrant x;auto pth="rewardGrants["+std::to_string(i)+"]";idf(*o,"id",pth,c,x.id);ui(*o,"experience",pth,c,x.experience);ui(*o,"gold",pth,c,x.gold);auto*l=req(*o,"items",pth,c);if(l){if(auto*ar=std::get_if<JsonArray>(&l->value)){for(size_t j=0;j<ar->size();++j){const JsonObject*q;if(!object((*ar)[j],pth+".items["+std::to_string(j)+"]",c,q))continue;AuthoredRewardItemGrant z;auto pp=pth+".items["+std::to_string(j)+"]";idf(*q,"itemId",pp,c,z.itemId);ui(*q,"quantity",pp,c,z.quantity);fields(*q,{"itemId","quantity"},pp,c);x.items.push_back(z);}}else c.error(*l,pth+".items","must be an array");}fields(*o,{"id","experience","gold","items"},pth,c);out.rewardGrants.push_back(std::move(x));}}
const char* unsupported[]={"projectiles","attacks","enemies","objects","pickups","npcs","dialogues","quests","tileSemantics","stamps"};for(auto n:unsupported){if(auto a=cat(n);a&&!a->empty()){c.error(*field(*root,n),n,"category decoding is not implemented in 13A1");}}if(c.d.empty())r.content=std::move(out);r.diagnostics.insert(r.diagnostics.end(),c.d.begin(),c.d.end());return r;}
}
