#include "game/content/content_json.h"
#include "engine/data/json.h"
#include <charconv>
#include <limits>

namespace underworld::game::content { namespace {
#define f(...) find(__VA_ARGS__)
using engine::data::JsonArray; using engine::data::JsonObject; using engine::data::JsonNumber; using engine::data::JsonValue;
struct Ctx { std::vector<ContentJsonDiagnostic> d; void e(const JsonValue&v,std::string p,std::string m){d.push_back({v.span.begin.line,v.span.begin.column,std::move(p),std::move(m)});} };
const JsonValue* f(const JsonObject&o,std::string_view n){for(auto&m:o)if(m.first==n)return &m.second;return nullptr;}
const JsonValue* req(const JsonValue&p,const JsonObject&o,std::string_view n,std::string_view path,Ctx&c){if(auto*v=f(o,n))return v;c.e(p,std::string(path)+"."+std::string(n),"missing required field");return nullptr;}
bool obj(const JsonValue&v,std::string_view p,Ctx&c,const JsonObject*&o){o=std::get_if<JsonObject>(&v.value);if(!o)c.e(v,std::string(p),"must be an object");return o!=nullptr;}
void fields(const JsonObject&o,std::initializer_list<std::string_view>a,std::string_view p,Ctx&c){for(auto&m:o){bool ok=false;for(auto n:a)ok|=m.first==n;if(!ok)c.e(m.second,std::string(p)+"."+m.first,"unknown field");}}
bool text(const JsonValue&v,std::string_view p,Ctx&c,std::string&o){if(auto*s=std::get_if<std::string>(&v.value)){o=*s;return true;}c.e(v,std::string(p),"must be a string");return false;}
#define text(...) underworld::game::content::text(__VA_ARGS__)
bool num(const JsonValue&v,std::string_view p,Ctx&c,std::uint64_t&o){auto*n=std::get_if<JsonNumber>(&v.value);if(!n){c.e(v,std::string(p),"must be an unsigned integer");return false;}auto [e,x]=std::from_chars(n->lexeme.data(),n->lexeme.data()+n->lexeme.size(),o);if(x!=std::errc{}||e!=n->lexeme.data()+n->lexeme.size()){c.e(v,std::string(p),"invalid unsigned integer");return false;}return true;}
bool snum(const JsonValue&v,std::string_view p,Ctx&c,std::int64_t&o){auto*n=std::get_if<JsonNumber>(&v.value);if(!n){c.e(v,std::string(p),"must be a signed integer");return false;}auto [e,x]=std::from_chars(n->lexeme.data(),n->lexeme.data()+n->lexeme.size(),o);if(x!=std::errc{}||e!=n->lexeme.data()+n->lexeme.size()){c.e(v,std::string(p),"invalid signed integer");return false;}return true;}
template<class T> bool un(const JsonValue&p,const JsonObject&o,std::string_view n,std::string_view path,Ctx&c,T&r){auto*v=req(p,o,n,path,c);if(!v)return false;std::uint64_t x{};if(!num(*v,std::string(path)+"."+std::string(n),c,x))return false;if(x>std::numeric_limits<T>::max()){c.e(*v,std::string(path)+"."+std::string(n),"outside field range");return false;}r=static_cast<T>(x);return true;}
template<class T> bool si(const JsonValue&p,const JsonObject&o,std::string_view n,std::string_view path,Ctx&c,T&r){auto*v=req(p,o,n,path,c);if(!v)return false;std::int64_t x{};if(!snum(*v,std::string(path)+"."+std::string(n),c,x))return false;if(x<std::numeric_limits<T>::min()||x>std::numeric_limits<T>::max()){c.e(*v,std::string(path)+"."+std::string(n),"outside field range");return false;}r=static_cast<T>(x);return true;}
bool did(const JsonValue&p,const JsonObject&o,std::string_view n,std::string_view path,Ctx&c,simulation::DefinitionId&r){auto*v=req(p,o,n,path,c);std::string s;return v&&text(*v,std::string(path)+"."+std::string(n),c,s)?(r=simulation::DefinitionId{s},true):false;}
bool category(const JsonValue&v,std::string_view p,Ctx&c,gameplay::ItemCategory&r){std::string s;if(!text(v,p,c,s))return false;if(s=="consumable")r=gameplay::ItemCategory::consumable;else if(s=="equipment")r=gameplay::ItemCategory::equipment;else if(s=="key")r=gameplay::ItemCategory::key;else if(s=="misc")r=gameplay::ItemCategory::misc;else{c.e(v,std::string(p),"unknown ItemCategory");return false;}return true;}
bool useKind(const JsonValue&v,std::string_view p,Ctx&c,gameplay::ItemUseKind&r){std::string s;if(!text(v,p,c,s))return false;if(s!="restoreHealth"){c.e(v,std::string(p),"unknown ItemUseKind");return false;}r=gameplay::ItemUseKind::restoreHealth;return true;}
bool equip(const JsonValue&v,std::string_view p,Ctx&c,AuthoredEquipmentSlot&r){std::string s;if(!text(v,p,c,s))return false;if(s=="armor")r=AuthoredEquipmentSlot::armor;else if(s=="accessory")r=AuthoredEquipmentSlot::accessory;else{c.e(v,std::string(p),"unknown equipment slot");return false;}return true;}
bool color(const JsonValue&v,std::string p,Ctx&c,core::ColorRGBA8&r){const JsonObject*o;if(!obj(v,p,c,o))return false;fields(*o,{"r","g","b","a"},p,c);return un(v,*o,"r",p,c,r.r)&&un(v,*o,"g",p,c,r.g)&&un(v,*o,"b",p,c,r.b)&&un(v,*o,"a",p,c,r.a);}
bool item(const JsonValue&v,std::string p,Ctx&c,AuthoredItem&r){const JsonObject*o;if(!obj(v,p,c,o))return false;fields(*o,{"id","visualId","category","stackLimit","use","equipment"},p,c);bool ok=did(v,*o,"id",p,c,r.id);ok=did(v,*o,"visualId",p,c,r.visualId)&&ok;auto*cv=req(v,*o,"category",p,c);ok=cv&&category(*cv,p+".category",c,r.category)&&ok;ok=un(v,*o,"stackLimit",p,c,r.stackLimit)&&ok;if(auto*u=f(*o,"use");u&&!std::holds_alternative<std::nullptr_t>(u->value)){const JsonObject*q;if(!obj(*u,p+".use",c,q)){ok=false;}else{fields(*q,{"kind","amount"},p+".use",c);auto*k=req(*u,*q,"kind",p+".use",c);std::int64_t a{};gameplay::ItemUseKind kind{};bool x=k&&useKind(*k,p+".use.kind",c,kind)&&si(*u,*q,"amount",p+".use",c,a);if(x)r.use=gameplay::ItemUseDefinition{kind,static_cast<int>(a)};ok=x&&ok;}}if(auto*e=f(*o,"equipment");e&&!std::holds_alternative<std::nullptr_t>(e->value)){const JsonObject*q;if(!obj(*e,p+".equipment",c,q)){ok=false;}else{fields(*q,{"slot","modifiers"},p+".equipment",c);auto*s=req(*e,*q,"slot",p+".equipment",c);auto*m=req(*e,*q,"modifiers",p+".equipment",c);AuthoredEquipment z{};bool x=s&&equip(*s,p+".equipment.slot",c,z.slot);const JsonObject*mo;if(!m||!obj(*m,p+".equipment.modifiers",c,mo))x=false;else{fields(*mo,{"maximumHealthBonus","playerAttackDamageBonus"},p+".equipment.modifiers",c);x=si(*m,*mo,"maximumHealthBonus",p+".equipment.modifiers",c,z.modifiers.maximumHealthBonus)&&x;x=si(*m,*mo,"playerAttackDamageBonus",p+".equipment.modifiers",c,z.modifiers.playerAttackDamageBonus)&&x;}if(x)r.equipment=z;ok=x&&ok;}}return ok;}
bool npc(const JsonValue&v,std::string p,Ctx&c,AuthoredNpcVisualSet&r){const JsonObject*o;if(!obj(v,p,c,o))return false;fields(*o,{"id","markerColor"},p,c);auto*m=req(v,*o,"markerColor",p,c);return did(v,*o,"id",p,c,r.id)&&m&&color(*m,p+".markerColor",c,r.markerColor);}
}
ContentJsonDecodeResult decodeAuthoredContentJson(std::string_view text){ContentJsonDecodeResult r;auto q=engine::data::parseJson(text);for(auto&d:q.diagnostics)r.diagnostics.push_back({d.location.line,d.location.column,{},d.message});if(!q.value)return r;const JsonObject*root=std::get_if<JsonObject>(&q.value->value);if(!root){r.diagnostics.push_back({1,1,{},"top-level JSON value must be an object"});return r;}Ctx c;std::string fmt;std::uint64_t version{};auto*f=f(*root,"format");auto*v=f(*root,"version");if(!f||!text(*f,"format",c,fmt)||fmt!="dungeon-underworld-content")c.e(*q.value,"format","invalid format");if(!v||!num(*v,"version",c,version)||version!=1)c.e(*q.value,"version","unsupported schema version");AuthoredContentPack out;auto cat=[&](const char*n){auto*x=f(*root,n);return x?std::get_if<JsonArray>(&x->value):nullptr;};if(auto*a=cat("items"))for(size_t i=0;i<a->size();++i){AuthoredItem x;if(item((*a)[i],"items["+std::to_string(i)+"]",c,x))out.items.push_back(std::move(x));}if(auto*a=cat("npcVisuals"))for(size_t i=0;i<a->size();++i){AuthoredNpcVisualSet x;if(npc((*a)[i],"npcVisuals["+std::to_string(i)+"]",c,x))out.npcVisuals.push_back(std::move(x));}for(const auto n:{"projectiles","attacks","enemies","objects","pickups","npcs","dialogues","quests","tileSemantics","stamps"})if(auto*x=f(*root,n);x&&std::holds_alternative<JsonArray>(x->value)&&!std::get<JsonArray>(x->value).empty())c.e(*x,n,"category decoding is not implemented in 13A1");if(c.d.empty())r.content=std::move(out);r.diagnostics.insert(r.diagnostics.end(),c.d.begin(),c.d.end());return r;}
} // namespace underworld::game::content
