#include "game/content/content_json.h"
#include "engine/data/json.h"
#include <charconv>
#include <fstream>
#include <limits>
#include <sstream>
#include <type_traits>

namespace underworld::game::content {
namespace {
using engine::data::JsonArray; using engine::data::JsonObject; using engine::data::JsonValue; using engine::data::JsonNumber;
JsonValue str(std::string value) { return { {}, std::move(value) }; }
JsonValue num(std::uint64_t value) { return { {}, JsonNumber{std::to_string(value)} }; }
JsonValue object(JsonObject value) { return { {}, std::move(value) }; }
JsonValue array(JsonArray value) { return { {}, std::move(value) }; }
void put(JsonObject& o, std::string key, JsonValue value) { o.emplace_back(std::move(key), std::move(value)); }
std::string id(const simulation::DefinitionId& value) { return std::string(value.value()); }
const JsonValue* field(const JsonValue& value, std::string_view name, std::string& error) { const auto* result=value.find(name); if(!result) error="missing field '"+std::string(name)+"'"; return result; }
bool stringField(const JsonValue& value, std::string_view name, std::string& out, std::string& error) { const auto* v=field(value,name,error); if(!v)return false; const auto* s=std::get_if<std::string>(&v->value); if(!s){error="field must be a string";return false;}out=*s;return true; }
bool uintField(const JsonValue& value, std::string_view name, std::uint64_t& out, std::string& error) { const auto* v=field(value,name,error); if(!v)return false; const auto* n=std::get_if<JsonNumber>(&v->value); if(!n){error="field must be an integer";return false;} const auto [p,e]=std::from_chars(n->lexeme.data(),n->lexeme.data()+n->lexeme.size(),out); if(e!=std::errc{}||p!=n->lexeme.data()+n->lexeme.size()){error="field is outside unsigned integer range";return false;}return true; }
JsonValue itemJson(const AuthoredItem& v) { JsonObject o; put(o,"id",str(id(v.id)));put(o,"visualId",str(id(v.visualId)));put(o,"category",str(v.category==gameplay::ItemCategory::consumable?"consumable":v.category==gameplay::ItemCategory::equipment?"equipment":v.category==gameplay::ItemCategory::key?"key":"misc"));put(o,"stackLimit",num(v.stackLimit));if(v.use){JsonObject u;put(u,"kind",str("restoreHealth"));put(u,"amount",num(static_cast<std::uint64_t>(v.use->amount)));put(o,"use",object(std::move(u)));}else put(o,"use",{ {}, nullptr });return object(std::move(o)); }
JsonValue shopJson(const AuthoredShop& v) { JsonObject o;put(o,"id",str(id(v.id)));JsonArray offers;for(const auto& x:v.offers){JsonObject q;put(q,"itemId",str(id(x.itemId)));if(x.playerBuyPrice)put(q,"playerBuyPrice",num(*x.playerBuyPrice));if(x.playerSellPrice)put(q,"playerSellPrice",num(*x.playerSellPrice));offers.push_back(object(std::move(q)));}put(o,"offers",array(std::move(offers)));return object(std::move(o)); }
bool decodeItem(const JsonValue& v, AuthoredItem& out, std::string& e) { std::string s;std::uint64_t n{};if(!stringField(v,"id",s,e))return false;out.id=simulation::DefinitionId{s};if(!stringField(v,"visualId",s,e))return false;out.visualId=simulation::DefinitionId{s};if(!stringField(v,"category",s,e))return false;if(s=="consumable")out.category=gameplay::ItemCategory::consumable;else if(s=="equipment")out.category=gameplay::ItemCategory::equipment;else if(s=="key")out.category=gameplay::ItemCategory::key;else if(s=="misc")out.category=gameplay::ItemCategory::misc;else{e="unknown item category";return false;}if(!uintField(v,"stackLimit",n,e)||n>std::numeric_limits<std::uint32_t>::max())return false;out.stackLimit=static_cast<std::uint32_t>(n);return true; }
bool decodeShop(const JsonValue& v, AuthoredShop& out, std::string& e) {std::string s;if(!stringField(v,"id",s,e))return false;out.id=simulation::DefinitionId{s};const auto* a=field(v,"offers",e);if(!a)return false;const auto* values=std::get_if<JsonArray>(&a->value);if(!values){e="offers must be an array";return false;}for(const auto& x:*values){AuthoredShopOffer offer;if(!stringField(x,"itemId",s,e))return false;offer.itemId=simulation::DefinitionId{s};const auto* b=x.find("playerBuyPrice");if(b){std::uint64_t n{};const auto* q=std::get_if<JsonNumber>(&b->value);if(!q){e="price must be an integer";return false;}auto [p,ec]=std::from_chars(q->lexeme.data(),q->lexeme.data()+q->lexeme.size(),n);if(ec!=std::errc{}||p!=q->lexeme.data()+q->lexeme.size()){e="invalid price";return false;}offer.playerBuyPrice=n;}const auto* c=x.find("playerSellPrice");if(c){std::uint64_t n{};const auto* q=std::get_if<JsonNumber>(&c->value);if(!q){e="price must be an integer";return false;}auto [p,ec]=std::from_chars(q->lexeme.data(),q->lexeme.data()+q->lexeme.size(),n);if(ec!=std::errc{}||p!=q->lexeme.data()+q->lexeme.size()){e="invalid price";return false;}offer.playerSellPrice=n;}out.offers.push_back(std::move(offer));}return true;}
}
std::string encodeAuthoredContentJson(const AuthoredContentPack& content) { JsonObject root;put(root,"format",str("dungeon-underworld-content"));put(root,"version",num(1));const char* names[]={"tilesets","projectiles","attacks","behaviors","enemies","items","objects","pickups","npcVisuals","npcs","dialogues","quests","playerProgressions","rewardProfiles","rewardGrants","shops","authoringDescriptors","tileSemantics","stamps"};for(const char* name:names){if(std::string_view{name}=="items"){JsonArray a;for(const auto& v:content.items)a.push_back(itemJson(v));put(root,name,array(std::move(a)));}else if(std::string_view{name}=="shops"){JsonArray a;for(const auto& v:content.shops)a.push_back(shopJson(v));put(root,name,array(std::move(a)));}else put(root,name,array({}));}return engine::data::writeJson(object(std::move(root))); }
ContentJsonDecodeResult decodeAuthoredContentJson(std::string_view text) { ContentJsonDecodeResult result;auto parsed=engine::data::parseJson(text);for(const auto& d:parsed.diagnostics)result.diagnostics.push_back({d.location.line,d.location.column,{},d.message});if(!parsed.value)return result;const auto& root=*parsed.value;if(!std::holds_alternative<JsonObject>(root.value)){result.diagnostics.push_back({1,1,{},"top-level JSON value must be an object"});return result;}const auto* format=root.find("format");const auto* version=root.find("version");if(!format||!version){result.diagnostics.push_back({1,1,{},"format and version are required"});return result;}const auto* fs=std::get_if<std::string>(&format->value);const auto* vn=std::get_if<JsonNumber>(&version->value);if(!fs||*fs!="dungeon-underworld-content"||!vn||vn->lexeme!="1"){result.diagnostics.push_back({format->span.begin.line,format->span.begin.column,{},"unsupported content format or version"});return result;}auto pack=AuthoredContentPack{};for(const auto& member:std::get<JsonObject>(root.value)){if(member.first=="format"||member.first=="version")continue;const char* known[]={"tilesets","projectiles","attacks","behaviors","enemies","items","objects","pickups","npcVisuals","npcs","dialogues","quests","playerProgressions","rewardProfiles","rewardGrants","shops","authoringDescriptors","tileSemantics","stamps"};bool accepted=false;for(const char* name:known)if(member.first==name)accepted=true;if(!accepted){result.diagnostics.push_back({member.second.span.begin.line,member.second.span.begin.column,member.first,"unknown top-level field"});continue;}const auto* values=std::get_if<JsonArray>(&member.second.value);if(!values){result.diagnostics.push_back({member.second.span.begin.line,member.second.span.begin.column,member.first,"category must be an array"});continue;}if(member.first=="items")for(std::size_t i=0;i<values->size();++i){AuthoredItem value;std::string e;if(!decodeItem((*values)[i],value,e))result.diagnostics.push_back({(*values)[i].span.begin.line,(*values)[i].span.begin.column,"items["+std::to_string(i)+"]",e});else pack.items.push_back(std::move(value));}if(member.first=="shops")for(std::size_t i=0;i<values->size();++i){AuthoredShop value;std::string e;if(!decodeShop((*values)[i],value,e))result.diagnostics.push_back({(*values)[i].span.begin.line,(*values)[i].span.begin.column,"shops["+std::to_string(i)+"]",e});else pack.shops.push_back(std::move(value));}}if(result.diagnostics.empty())result.content=std::move(pack);return result;}
ContentJsonDecodeResult readAuthoredContentJsonFile(const std::filesystem::path& path){std::ifstream input(path,std::ios::binary);if(!input)return {{},{{0,0,path.string(),"could not open content file"}}};std::ostringstream text;text<<input.rdbuf();return decodeAuthoredContentJson(text.str());}
bool writeAuthoredContentJsonFile(const std::filesystem::path& path,const AuthoredContentPack& content,std::string& error){std::ofstream output(path,std::ios::binary);if(!output){error="could not open content file for writing";return false;}output<<encodeAuthoredContentJson(content);if(!output){error="could not write content file";return false;}error.clear();return true;}
} // namespace underworld::game::content
