#include "game/maps/authored_map.h"

#include "engine/data/json.h"

#include <charconv>
#include <fstream>
#include <limits>
#include <sstream>

namespace underworld::game::maps {
namespace {
using engine::data::JsonArray; using engine::data::JsonNumber; using engine::data::JsonObject;
using engine::data::JsonValue;
JsonValue s(std::string v) { return {{}, std::move(v)}; }
JsonValue n(std::int64_t v) { return {{}, JsonNumber{std::to_string(v)}}; }
JsonValue u(std::uint64_t v) { return {{}, JsonNumber{std::to_string(v)}}; }
JsonValue b(bool v) { return {{}, v}; }
JsonValue o(JsonObject v) { return {{}, std::move(v)}; }
JsonValue a(JsonArray v) { return {{}, std::move(v)}; }
void put(JsonObject& x, std::string key, JsonValue value) { x.emplace_back(std::move(key), std::move(value)); }
JsonValue id(std::string_view value) { return s(std::string(value)); }
JsonValue point(core::WorldPointI p) { JsonObject x; put(x,"x",n(p.x)); put(x,"y",n(p.y)); return o(std::move(x)); }
JsonValue area(world::AabbI p) { JsonObject x; put(x,"x",n(p.x)); put(x,"y",n(p.y)); put(x,"width",n(p.width)); put(x,"height",n(p.height)); return o(std::move(x)); }
std::string facing(gameplay::FacingDirection v) { switch(v){case gameplay::FacingDirection::down:return "down";case gameplay::FacingDirection::up:return "up";case gameplay::FacingDirection::left:return "left";case gameplay::FacingDirection::right:return "right";} return "down"; }
bool parseI(const JsonValue& v, std::int64_t& out) { const auto* x=std::get_if<JsonNumber>(&v.value); if(!x)return false; const auto r=std::from_chars(x->lexeme.data(),x->lexeme.data()+x->lexeme.size(),out); return r.ec==std::errc{}&&r.ptr==x->lexeme.data()+x->lexeme.size(); }
bool parseU(const JsonValue& v, std::uint64_t& out) { std::int64_t x{}; if(!parseI(v,x)||x<0)return false; out=static_cast<std::uint64_t>(x); return true; }
const JsonValue* field(const JsonObject& x,std::string_view key){for(const auto& p:x)if(p.first==key)return &p.second;return nullptr;}
struct Reader { std::vector<AuthoredMapDiagnostic> d; void error(const JsonValue& v,std::string path,std::string code,std::string msg){d.push_back({AuthoredMapDiagnosticStage::decode,std::move(code),std::move(msg),std::move(path),v.span.begin.line,v.span.begin.column});} };
const JsonObject* object(const JsonValue& v,Reader& r,const std::string& p){auto* x=std::get_if<JsonObject>(&v.value);if(!x)r.error(v,p,"wrong_type","must be an object");return x;}
const JsonArray* array(const JsonValue& v,Reader& r,const std::string& p){auto* x=std::get_if<JsonArray>(&v.value);if(!x)r.error(v,p,"wrong_type","must be an array");return x;}
const JsonValue* req(const JsonObject& x,const JsonValue& parent,Reader& r,const std::string& p,std::string_view key){const auto* v=field(x,key);if(!v)r.error(parent,p+"."+std::string(key),"missing_required","missing required field");return v;}
bool text(const JsonValue& v,Reader& r,const std::string& p,std::string& out){auto* x=std::get_if<std::string>(&v.value);if(!x){r.error(v,p,"wrong_type","must be a string");return false;}out=*x;return !out.empty();}
bool pointRead(const JsonValue& v,Reader& r,const std::string& p,core::WorldPointI& out){auto*x=object(v,r,p);if(!x)return false;const auto*a=req(*x,v,r,p,"x"),*b=req(*x,v,r,p,"y");std::int64_t i{},j{};bool ok=a&&parseI(*a,i);if(!ok&&a)r.error(*a,p+".x","invalid_integer","must be an integer");ok=b&&parseI(*b,j)&&ok;if(!ok&&b&&!parseI(*b,j))r.error(*b,p+".y","invalid_integer","must be an integer");if(ok){if(i<std::numeric_limits<int>::min()||i>std::numeric_limits<int>::max()||j<std::numeric_limits<int>::min()||j>std::numeric_limits<int>::max())return false;out={static_cast<int>(i),static_cast<int>(j)};}return ok;}
bool areaRead(const JsonValue& v,Reader& r,const std::string& p,world::AabbI& out){auto*x=object(v,r,p);if(!x)return false;std::int64_t q[4]{};bool ok=true;const char* keys[]={"x","y","width","height"};for(int i=0;i<4;++i){const auto*z=req(*x,v,r,p,keys[i]);if(!z||!parseI(*z,q[i])){if(z)r.error(*z,p+"."+keys[i],"invalid_integer","must be an integer");ok=false;}}if(ok&&q[0]>=std::numeric_limits<int>::min()&&q[0]<=std::numeric_limits<int>::max()&&q[1]>=std::numeric_limits<int>::min()&&q[1]<=std::numeric_limits<int>::max()&&q[2]>=std::numeric_limits<int>::min()&&q[2]<=std::numeric_limits<int>::max()&&q[3]>=std::numeric_limits<int>::min()&&q[3]<=std::numeric_limits<int>::max()){out={static_cast<int>(q[0]),static_cast<int>(q[1]),static_cast<int>(q[2]),static_cast<int>(q[3])};}else ok=false;return ok;}
bool definitionId(const JsonValue& v,Reader& r,const std::string& p,simulation::DefinitionId& out){std::string x;if(!text(v,r,p,x))return false;out=simulation::DefinitionId{std::move(x)};return true;}
bool mapId(const JsonValue& v,Reader& r,const std::string& p,simulation::MapId& out){std::string x;if(!text(v,r,p,x))return false;out=simulation::MapId{std::move(x)};return true;}
bool facingRead(const JsonValue& v,Reader& r,const std::string& p,gameplay::FacingDirection& out){std::string x;if(!text(v,r,p,x))return false;if(x=="down")out=gameplay::FacingDirection::down;else if(x=="up")out=gameplay::FacingDirection::up;else if(x=="left")out=gameplay::FacingDirection::left;else if(x=="right")out=gameplay::FacingDirection::right;else{r.error(v,p,"unknown_enum","unknown facing direction");return false;}return true;}
JsonValue placementId(std::uint64_t v){return u(v);}
const char* triggerName(WorldTriggerKind v){switch(v){case WorldTriggerKind::mapEntered:return "mapEntered";case WorldTriggerKind::regionEntered:return "regionEntered";case WorldTriggerKind::regionExited:return "regionExited";case WorldTriggerKind::encounterStarted:return "encounterStarted";case WorldTriggerKind::encounterCompleted:return "encounterCompleted";case WorldTriggerKind::objectOpened:return "objectOpened";}return "mapEntered";}
const char* conditionName(WorldConditionKind v){switch(v){case WorldConditionKind::flagSet:return "flagSet";case WorldConditionKind::flagNotSet:return "flagNotSet";case WorldConditionKind::encounterCompleted:return "encounterCompleted";case WorldConditionKind::encounterNotCompleted:return "encounterNotCompleted";case WorldConditionKind::doorState:return "doorState";}return "flagSet";}
const char* actionName(WorldActionKind v){switch(v){case WorldActionKind::setFlag:return "setFlag";case WorldActionKind::clearFlag:return "clearFlag";case WorldActionKind::startEncounter:return "startEncounter";case WorldActionKind::setDoorState:return "setDoorState";}return "setFlag";}
const char* doorName(DoorState v){switch(v){case DoorState::locked:return "locked";case DoorState::closed:return "closed";case DoorState::open:return "open";}return "closed";}
void addAllowed(const JsonObject& x,Reader& r,const std::string& p,std::initializer_list<std::string_view> keys){for(const auto& m:x){bool found=false;for(auto k:keys)if(m.first==k)found=true;if(!found)r.error(m.second,p+"."+m.first,"unknown_field","unknown field");}}
bool readPlacement(const JsonValue& v,Reader& r,const std::string& p,simulation::PersistentInstanceId& idOut,simulation::DefinitionId& def,core::WorldPointI& pos,gameplay::FacingDirection& face){auto*x=object(v,r,p);if(!x)return false;addAllowed(*x,r,p,{"id","definitionId","position","facing"});bool ok=true;auto*i=req(*x,v,r,p,"id"),*d=req(*x,v,r,p,"definitionId"),*q=req(*x,v,r,p,"position"),*f=req(*x,v,r,p,"facing");std::uint64_t n0{};ok=i&&parseU(*i,n0)&&n0!=0;if(i&&!ok)r.error(*i,p+".id","invalid_id","invalid persistent id");ok=d&&definitionId(*d,r,p+".definitionId",def)&&ok;ok=q&&pointRead(*q,r,p+".position",pos)&&ok;ok=f&&facingRead(*f,r,p+".facing",face)&&ok;idOut.value=n0;return ok;}
}

std::string encodeAuthoredMapJson(const AuthoredMapSource& source) {
    const auto& m=source.map; JsonObject root; put(root,"format",s("dungeon-underworld-map-source"));put(root,"version",u(1));put(root,"id",id(m.id.value()));put(root,"width",u(m.width));put(root,"height",u(m.height));put(root,"tileSize",u(m.tileSize));
    JsonArray refs;for(const auto& x:m.tileReferences){JsonObject q;put(q,"tilesetId",id(x.tilesetId.value()));put(q,"sourceIndex",u(x.sourceIndex));put(q,"flags",u(static_cast<std::uint8_t>(x.flags)));refs.push_back(o(std::move(q)));}put(root,"tileReferences",a(std::move(refs)));
    JsonArray layers;for(const auto& x:m.layers){JsonObject q;put(q,"name",s(x.name));put(q,"visible",b(x.visible));JsonArray cells;for(const auto& c:x.cells)cells.push_back(c?u(*c):JsonValue{{},nullptr});put(q,"cells",a(std::move(cells)));layers.push_back(o(std::move(q)));}put(root,"layers",a(std::move(layers)));JsonArray collision;for(auto x:m.collision)collision.push_back(u(x));put(root,"collision",a(std::move(collision)));
    JsonArray spawns;for(const auto& x:m.playerSpawns){JsonObject q;put(q,"id",s(std::string(x.id.value())));put(q,"position",point(x.position));put(q,"facing",s(facing(x.facing)));spawns.push_back(o(std::move(q)));}put(root,"playerSpawns",a(std::move(spawns)));
    JsonArray enemies;for(const auto& x:m.enemies){JsonObject q;put(q,"id",placementId(x.id.value));put(q,"definitionId",id(x.definitionId.value()));put(q,"position",point(x.position));put(q,"facing",s(facing(x.facing)));enemies.push_back(o(std::move(q)));}put(root,"enemies",a(std::move(enemies)));
    JsonArray regions;for(const auto& x:m.regions){JsonObject q;put(q,"id",id(x.id.value()));put(q,"bounds",area(x.bounds));regions.push_back(o(std::move(q)));}put(root,"regions",a(std::move(regions)));
    JsonArray encounters;for(const auto& x:m.encounters){JsonObject q;put(q,"id",id(x.id.value()));JsonArray p;for(auto v:x.participants)p.push_back(u(v.value));put(q,"participants",a(std::move(p)));if(x.rewardGrantId)put(q,"rewardGrantId",id(x.rewardGrantId->value()));encounters.push_back(o(std::move(q)));}put(root,"encounters",a(std::move(encounters)));
    JsonArray rules;for(const auto& x:m.worldRules){JsonObject q,tg;put(q,"id",id(x.id.value()));put(q,"once",b(x.once));put(tg,"kind",s(triggerName(x.trigger.kind)));put(tg,"target",id(x.trigger.target.value()));put(q,"trigger",o(std::move(tg)));JsonArray cs;for(const auto& c:x.conditions){JsonObject z;put(z,"kind",s(conditionName(c.kind)));put(z,"target",id(c.target.value()));put(z,"doorState",s(doorName(c.doorState)));cs.push_back(o(std::move(z)));}put(q,"conditions",a(std::move(cs)));JsonArray as;for(const auto& ac:x.actions){JsonObject z;put(z,"kind",s(actionName(ac.kind)));put(z,"target",id(ac.target.value()));put(z,"doorState",s(doorName(ac.doorState)));as.push_back(o(std::move(z)));}put(q,"actions",a(std::move(as)));rules.push_back(o(std::move(q)));}put(root,"worldRules",a(std::move(rules)));
    return engine::data::writeJson({{},std::move(root)});
}

AuthoredMapDecodeResult decodeAuthoredMapJson(std::string_view json) {
    AuthoredMapDecodeResult result;auto parsed=engine::data::parseJson(json);for(const auto& x:parsed.diagnostics)result.diagnostics.push_back({AuthoredMapDiagnosticStage::decode,"json_parse",x.message,{},x.location.line,x.location.column});if(!parsed.value||!result.diagnostics.empty())return result;Reader r;auto* root=object(*parsed.value,r,"");if(!root)return result;addAllowed(*root,r,"",{"format","version","id","width","height","tileSize","tileReferences","layers","collision","playerSpawns","enemies","regions","worldRules","encounters"});const auto*f=req(*root,*parsed.value,r,"format","format"),*v=req(*root,*parsed.value,r,"version","version"),*i=req(*root,*parsed.value,r,"id","id"),*w=req(*root,*parsed.value,r,"width","width"),*h=req(*root,*parsed.value,r,"height","height"),*t=req(*root,*parsed.value,r,"tileSize","tileSize"),*l=req(*root,*parsed.value,r,"layers","layers"),*c=req(*root,*parsed.value,r,"collision","collision"),*p=req(*root,*parsed.value,r,"playerSpawns","playerSpawns");std::string fs;std::uint64_t ver=0;AuthoredMapSource source;bool ok=f&&text(*f,r,"format",fs)&&fs=="dungeon-underworld-map-source";if(f&&fs!="dungeon-underworld-map-source")r.error(*f,"format","invalid_format","invalid format identifier");ok=v&&parseU(*v,ver)&&ver==1&&ok;if(v&&ver!=1)r.error(*v,"version","unsupported_version","unsupported map schema version");ok=i&&mapId(*i,r,"id",source.map.id)&&ok;std::uint64_t z{};ok=w&&parseU(*w,z)&&z<=MapLimits::maximumDimension&&ok;source.map.width=static_cast<std::uint32_t>(z);z=0;ok=h&&parseU(*h,z)&&z<=MapLimits::maximumDimension&&ok;source.map.height=static_cast<std::uint32_t>(z);z=0;ok=t&&parseU(*t,z)&&z<=std::numeric_limits<std::uint16_t>::max()&&ok;source.map.tileSize=static_cast<std::uint16_t>(z);
    const JsonArray* refs=nullptr; if(auto*x=field(*root,"tileReferences")){refs=array(*x,r,"tileReferences");if(refs)for(std::size_t n=0;n<refs->size();++n){auto*q=object((*refs)[n],r,"tileReferences["+std::to_string(n)+"]");if(!q){ok=false;continue;}auto*d=req(*q,(*refs)[n],r,"tileReferences["+std::to_string(n)+"]","tilesetId");auto*si=req(*q,(*refs)[n],r,"tileReferences["+std::to_string(n)+"]","sourceIndex");MapTileReference x{};std::uint64_t vv{};bool good=d&&definitionId(*d,r,"tileReferences["+std::to_string(n)+"].tilesetId",x.tilesetId);good=si&&parseU(*si,vv)&&vv<=std::numeric_limits<std::uint32_t>::max()&&good;x.sourceIndex=static_cast<std::uint32_t>(vv);source.map.tileReferences.push_back(std::move(x));ok=good&&ok;}} else ok=false;
    const JsonArray* la=nullptr;if(l&&(la=array(*l,r,"layers")))for(std::size_t n=0;n<la->size();++n){auto*q=object((*la)[n],r,"layers["+std::to_string(n)+"]");if(!q){ok=false;continue;}std::string name;auto*nv=req(*q,(*la)[n],r,"layers["+std::to_string(n)+"]","name"),*cv=req(*q,(*la)[n],r,"layers["+std::to_string(n)+"]","cells");bool vis=true;auto*vv=field(*q,"visible");if(vv){if(auto*x=std::get_if<bool>(&vv->value))vis=*x;else{r.error(*vv,"layers["+std::to_string(n)+"].visible","wrong_type","must be boolean");ok=false;}}bool good=nv&&text(*nv,r,"layers["+std::to_string(n)+"].name",name);const JsonArray* ca=cv?array(*cv,r,"layers["+std::to_string(n)+"].cells"):nullptr;if(!ca)good=false;MapTileLayer layer{std::move(name),vis,{}};if(ca)for(const auto& cell:*ca){if(std::holds_alternative<std::nullptr_t>(cell.value))layer.cells.push_back(std::nullopt);else{std::uint64_t ix{};if(parseU(cell,ix)&&ix<=std::numeric_limits<std::uint32_t>::max())layer.cells.push_back(static_cast<std::uint32_t>(ix));else{r.error(cell,"layers["+std::to_string(n)+"].cells","invalid_integer","invalid tile index");good=false;}}}source.map.layers.push_back(std::move(layer));ok=good&&ok;}else ok=false;
    const JsonArray* co=nullptr;if(c&&(co=array(*c,r,"collision")))for(const auto& cell:*co){std::uint64_t x{};if(parseU(cell,x)&&x<=1)source.map.collision.push_back(static_cast<std::uint8_t>(x));else{r.error(cell,"collision","invalid_value","collision cell must be 0 or 1");ok=false;}}else ok=false;
    const JsonArray* pa=nullptr;if(p&&(pa=array(*p,r,"playerSpawns")))for(std::size_t n=0;n<pa->size();++n){auto*q=object((*pa)[n],r,"playerSpawns["+std::to_string(n)+"]");if(!q){ok=false;continue;}std::string sid;auto*si=req(*q,(*pa)[n],r,"playerSpawns["+std::to_string(n)+"]","id"),*po=req(*q,(*pa)[n],r,"playerSpawns["+std::to_string(n)+"]","position"),*fa=req(*q,(*pa)[n],r,"playerSpawns["+std::to_string(n)+"]","facing");gameplay::FacingDirection face{};core::WorldPointI pos{};bool good=si&&text(*si,r,"playerSpawns["+std::to_string(n)+"].id",sid);good=po&&pointRead(*po,r,"playerSpawns["+std::to_string(n)+"].position",pos)&&good;good=fa&&facingRead(*fa,r,"playerSpawns["+std::to_string(n)+"].facing",face)&&good;if(good)source.map.playerSpawns.push_back({simulation::SpawnId{std::move(sid)},pos,face});ok=good&&ok;}else ok=false;
    if(auto*e=field(*root,"enemies")){if(auto*ea=array(*e,r,"enemies"))for(std::size_t n=0;n<ea->size();++n){simulation::PersistentInstanceId pid{};simulation::DefinitionId def{};core::WorldPointI pos{};gameplay::FacingDirection face{};if(readPlacement((*ea)[n],r,"enemies["+std::to_string(n)+"]",pid,def,pos,face))source.map.enemies.push_back({pid,std::move(def),pos,face});else ok=false;}};
    if(auto*rs=field(*root,"regions")){if(auto*ra=array(*rs,r,"regions"))for(std::size_t n=0;n<ra->size();++n){auto*q=object((*ra)[n],r,"regions["+std::to_string(n)+"]");if(!q){ok=false;continue;}MapRegionDefinition x{};auto*ii=req(*q,(*ra)[n],r,"regions["+std::to_string(n)+"]","id"),*bb=req(*q,(*ra)[n],r,"regions["+std::to_string(n)+"]","bounds");bool good=ii&&definitionId(*ii,r,"regions["+std::to_string(n)+"].id",x.id);good=bb&&areaRead(*bb,r,"regions["+std::to_string(n)+"].bounds",x.bounds)&&good;if(good)source.map.regions.push_back(std::move(x));ok=good&&ok;}};
    if(auto*en=field(*root,"encounters")){if(auto*ea=array(*en,r,"encounters"))for(std::size_t n=0;n<ea->size();++n){auto*q=object((*ea)[n],r,"encounters["+std::to_string(n)+"]");if(!q){ok=false;continue;}EncounterDefinition x{};auto*ii=req(*q,(*ea)[n],r,"encounters["+std::to_string(n)+"]","id"),*pp=req(*q,(*ea)[n],r,"encounters["+std::to_string(n)+"]","participants");bool good=ii&&definitionId(*ii,r,"encounters["+std::to_string(n)+"].id",x.id);const JsonArray* ids=pp?array(*pp,r,"encounters["+std::to_string(n)+"].participants"):nullptr;if(!ids)good=false;else for(const auto& y:*ids){std::uint64_t val{};if(parseU(y,val)&&val)x.participants.push_back({val});else{r.error(y,"encounters["+std::to_string(n)+"].participants","invalid_id","invalid participant id");good=false;}}if(good)source.map.encounters.push_back(std::move(x));ok=good&&ok;}};
    if(auto*ws=field(*root,"worldRules")){if(auto*wa=array(*ws,r,"worldRules"))for(std::size_t n=0;n<wa->size();++n){const auto path="worldRules["+std::to_string(n)+"]";auto*q=object((*wa)[n],r,path);if(!q){ok=false;continue;}WorldRuleDefinition rule{};auto*ii=req(*q,(*wa)[n],r,path,"id"),*tr=req(*q,(*wa)[n],r,path,"trigger"),*co=req(*q,(*wa)[n],r,path,"conditions"),*ac=req(*q,(*wa)[n],r,path,"actions");bool good=ii&&definitionId(*ii,r,path+".id",rule.id);if(auto*once=field(*q,"once")){if(auto*x=std::get_if<bool>(&once->value))rule.once=*x;else{r.error(*once,path+".once","wrong_type","must be boolean");good=false;}}else{r.error((*wa)[n],path+".once","missing_required","missing required field");good=false;}auto*to=tr?object(*tr,r,path+".trigger"):nullptr;if(!to)good=false;else{auto*k=req(*to,*tr,r,path+".trigger","kind"),*tg=req(*to,*tr,r,path+".trigger","target");std::string ks;if(!k||!text(*k,r,path+".trigger.kind",ks))good=false;else if(ks=="mapEntered")rule.trigger.kind=WorldTriggerKind::mapEntered;else if(ks=="regionEntered")rule.trigger.kind=WorldTriggerKind::regionEntered;else if(ks=="regionExited")rule.trigger.kind=WorldTriggerKind::regionExited;else if(ks=="encounterStarted")rule.trigger.kind=WorldTriggerKind::encounterStarted;else if(ks=="encounterCompleted")rule.trigger.kind=WorldTriggerKind::encounterCompleted;else if(ks=="objectOpened")rule.trigger.kind=WorldTriggerKind::objectOpened;else{r.error(*k,path+".trigger.kind","unknown_enum","unknown world trigger");good=false;}good=tg&&definitionId(*tg,r,path+".trigger.target",rule.trigger.target)&&good;}
        const JsonArray* ca=co?array(*co,r,path+".conditions"):nullptr;if(!ca)good=false;else for(std::size_t j=0;j<ca->size();++j){const auto cp=path+".conditions["+std::to_string(j)+"]";auto*z=object((*ca)[j],r,cp);if(!z){good=false;continue;}WorldCondition cnd{};auto*k=req(*z,(*ca)[j],r,cp,"kind"),*tg=req(*z,(*ca)[j],r,cp,"target");std::string ks;if(!k||!text(*k,r,cp+".kind",ks))good=false;else if(ks=="flagSet")cnd.kind=WorldConditionKind::flagSet;else if(ks=="flagNotSet")cnd.kind=WorldConditionKind::flagNotSet;else if(ks=="encounterCompleted")cnd.kind=WorldConditionKind::encounterCompleted;else if(ks=="encounterNotCompleted")cnd.kind=WorldConditionKind::encounterNotCompleted;else if(ks=="doorState")cnd.kind=WorldConditionKind::doorState;else{r.error(*k,cp+".kind","unknown_enum","unknown world condition");good=false;}good=tg&&definitionId(*tg,r,cp+".target",cnd.target)&&good;rule.conditions.push_back(std::move(cnd));}
        const JsonArray* aa=ac?array(*ac,r,path+".actions"):nullptr;if(!aa)good=false;else for(std::size_t j=0;j<aa->size();++j){const auto ap=path+".actions["+std::to_string(j)+"]";auto*z=object((*aa)[j],r,ap);if(!z){good=false;continue;}WorldAction act{};auto*k=req(*z,(*aa)[j],r,ap,"kind"),*tg=req(*z,(*aa)[j],r,ap,"target");std::string ks;if(!k||!text(*k,r,ap+".kind",ks))good=false;else if(ks=="setFlag")act.kind=WorldActionKind::setFlag;else if(ks=="clearFlag")act.kind=WorldActionKind::clearFlag;else if(ks=="startEncounter")act.kind=WorldActionKind::startEncounter;else if(ks=="setDoorState")act.kind=WorldActionKind::setDoorState;else{r.error(*k,ap+".kind","unknown_enum","unknown world action");good=false;}good=tg&&definitionId(*tg,r,ap+".target",act.target)&&good;rule.actions.push_back(std::move(act));}if(good)source.map.worldRules.push_back(std::move(rule));ok=good&&ok;}}
    if(r.d.empty()&&ok){const auto valid=validateMapData(source.map);if(!valid)r.error(*parsed.value,"","invalid_map",valid.error);}result.diagnostics=std::move(r.d);if(result.diagnostics.empty())result.source=std::move(source);return result;
}

AuthoredMapDecodeResult readAuthoredMapFile(const std::filesystem::path& path){std::ifstream in(path,std::ios::binary);if(!in)return {{},{{AuthoredMapDiagnosticStage::io,"open_failed","could not open authored map",path.string(),1,1}}};std::ostringstream text;text<<in.rdbuf();auto result=decodeAuthoredMapJson(text.str());for(auto& d:result.diagnostics)d.path=path.string()+ (d.path.empty()?"":":"+d.path);return result;}
bool writeAuthoredMapFile(const std::filesystem::path& path,const AuthoredMapSource& source,std::string& error){try{std::ofstream out(path,std::ios::binary|std::ios::trunc);if(!out){error="could not open authored map";return false;}const auto text=encodeAuthoredMapJson(source);out.write(text.data(),static_cast<std::streamsize>(text.size()));if(!out){error="could not write authored map";return false;}return true;}catch(const std::exception& e){error=e.what();return false;}}
MapCompileResult compileAuthoredMap(const AuthoredMapSource& source,const game::GameContentRegistry& content){const auto catalogs=game::mapValidationCatalogs(content);const auto valid=validateMapData(source.map,&catalogs);if(!valid)return {{},{{AuthoredMapDiagnosticStage::validation,"invalid_map",valid.error,"",1,1}}};return {source.map,{}};}
}
