from __future__ import annotations


TRANSLATIONS = {
    "pt-BR": {
        "app": "Dungeon Underworld — Content Studio",
        "map": "Mapa", "maps_mode": "Mapas", "content": "Conteúdo", "content_mode": "Conteúdos", "maps": "Mapas", "layers": "Camadas", "tiles": "Tiles",
        "entities": "Entidades", "spritesheets_animations": "Spritesheet / Animação", "inspector": "Inspetor", "diagnostics": "Diagnósticos",
        "new_project": "Novo Projeto", "open": "Abrir", "save": "Salvar", "save_as": "Salvar Como",
        "save_all": "Salvar Tudo", "validate": "Validar Workspace", "export": "Exportar DMAP",
        "playtest": "Playtest", "undo": "Desfazer", "redo": "Refazer", "grid": "Grade",
        "select": "Selecionar", "selection_deleted": "Seleção excluída", "pencil": "Lápis", "erase": "Apagar", "rectangle": "Retângulo",
        "fill": "Preencher", "collision": "Colisão", "entity": "Entidade", "region": "Região",
        "search": "Procurar", "project": "Projeto", "builtin": "Engine / Builtin",
        "create": "Criar", "delete": "Excluir", "duplicate": "Duplicar", "add": "Adicionar",
        "remove": "Remover", "rename": "Renomear", "entry_map": "Mapa de Entrada",
        "map_create": "Criar mapa", "map_edit_properties": "Propriedades do mapa", "map_name_id": "Nome / Map ID",
        "map_width_tiles": "Largura (tiles)", "map_height_tiles": "Altura (tiles)", "map_create_player_spawn": "Criar Player Spawn inicial",
        "map_folder": "Pasta", "map_no_folder": "Sem pasta",
        "map_new": "Novo mapa", "map_import": "Importar UMAP", "map_remove": "Excluir mapa", "map_set_entry": "Definir como entrada", "map_edit_properties_action": "Editar propriedades do mapa...",
        "map_resize_hint": "Ao redimensionar, tiles e colisões da área superior esquerda são preservados.", "map_id_required": "Informe o nome / Map ID.",
        "player_start_moved": "Player Start movido",
        "untitled": "Sem título", "no_selection": "Nenhuma seleção", "invalid": "Inválido",
        "file": "Arquivo", "edit": "Editar", "view": "Exibir", "tools": "Ferramentas",
        "new_content": "Novo Workspace de Conteúdo", "open_project": "Abrir Projeto...",
        "open_content": "Abrir Conteúdo", "quit": "Sair", "frame": "Enquadrar Mapa",
        "language": "Idioma", "definitions": "Definições", "assets": "Assets",
        "semantics_stamps": "Semântica / Stamps", "map_elements": "Elementos do Mapa", "scenes": "Cenas", "rules_links": "Regras / Links",
        "tools_select": "Selecionar", "tools_pencil": "Lápis", "tools_erase": "Apagar",
        "tools_rectangle": "Retângulo", "tools_fill": "Preencher", "tools_eyedropper": "Escolher Tile",
        "tools_tile_selection": "Selecionar Tiles", "tools_collision": "Colisão +",
        "tools_collision_erase": "Colisão -", "tools_collision_rectangle": "Colisão Ret +",
        "tools_collision_rectangle_erase": "Colisão Ret -", "tools_collision_fill": "Colisão Fill +",
        "tools_collision_fill_erase": "Colisão Fill -", "tools_entity": "Entidade",
        "tools_spawn": "Player Spawn", "tools_link": "Link de Mapa", "tools_region": "Região",
        "tools_stamp": "Stamp", "tools_pan": "Pan", "ready": "Pronto",
        "snap": "Snap", "overlays": "Sobreposições", "playtest_toolbar": "Playtest",
        "player_spawn": "Player Spawn", "map_transition": "Transição de Mapa", "region_element": "Região / Trigger",
        "map_elements_hint": "Arraste um elemento para o mapa", "tileset_import": "Importar Tileset", "import_tileset": "Importar Tileset...",
        "browse": "Procurar", "source_image": "Imagem fonte", "tileset_id": "ID do Tileset",
        "display_name": "Nome exibido", "tile_width": "Largura do tile", "tile_height": "Altura do tile",
        "spacing": "Espaçamento", "margin": "Margem", "copy_to_workspace": "Copiar para o workspace",
        "no_image": "Nenhuma imagem", "image_unavailable": "Imagem indisponível", "invalid_image": "Imagem inválida",
        "grid_summary": "{width} × {height} px — {columns} × {rows} frames ({frames} no total)", "grid_unused_edge": "Borda fora dos frames: {width} px à direita e {height} px abaixo. Essa área não será importada.",
        "frames_preview": "Prévia da divisão em frames", "frame_preview_help": "Cada linha azul fina marca somente o corte onde começa a próxima coluna ou linha de frames. A linha é apenas uma guia da prévia e não altera a imagem importada.", "frame_bounds": "Exemplo: o frame 0, no canto superior esquerdo, usa X {left} a {right} e Y {top} a {bottom}, totalizando {width} × {height} px.",
        "spritesheet_import": "Importar spritesheet...", "image_id": "ID da imagem", "animation_id": "ID da animação", "frame_width": "Largura do frame", "frame_height": "Altura do frame", "frame_duration": "Duração por frame (ticks)", "animation_preview": "Como ficará a animação", "play_animation": "Play", "pause_animation": "Pause", "no_animations": "Nenhuma animação importada", "animation_imported": "Spritesheet e animação importados", "edit_animation_frames": "Editar frames...", "edit_spritesheet_import": "Editar importação...", "animation_frame": "Frame", "frame_offset_x": "Deslocamento X", "frame_offset_y": "Deslocamento Y", "center_current_frame": "Centralizar este frame", "center_all_frames": "Centralizar todos", "reset_current_frame": "Restaurar este frame", "reset_all_frames": "Restaurar todos", "frame_alignment_help": "Arraste a imagem ou use as setas para mover o frame em passos de 1 pixel. A linha azul mostra a área original do frame e a cruz amarela mostra seu centro. O PNG original não será alterado.", "animation_frames_updated": "Alinhamento dos frames atualizado", "spritesheet_import_updated": "Configuração de importação atualizada",
        "tilesets": "Tilesets", "search_tilesets": "Procurar tilesets", "add_files": "Adicionar arquivos...",
        "add_folder": "Importar pasta...", "new_tileset_folder": "Nova pasta...", "reimport": "Reimportar", "reimported": "Tileset reimportado",
        "conflict": "Conflito", "skip": "Ignorar", "change_id": "Mudar ID", "incompatible": "incompatível",
        "tile_size": "Tamanho do tile", "default_tile_size": "Tamanho padrão", "apply_to_all": "Aplicar a todos", "tileset_grid": "Grade resultante",
        "manage_tileset": "Gerenciar tileset...", "tileset_properties_saved": "Propriedades do tileset atualizadas",
        "tileset_folder": "Pasta de tilesets", "tileset_no_folder": "Sem pasta", "tileset_folder_memberships": "Pastas organizacionais", "tileset_folder_memberships_hint": "Um tileset pode pertencer a mais de uma pasta.", "add_to_tileset_folder": "Adicionar à pasta", "remove_from_tileset_folder": "Remover desta pasta", "rename_tileset_folder": "Renomear pasta...", "delete_tileset_folder": "Excluir pasta", "tileset_folder_name": "Nome da pasta", "tileset_folder_exists": "Já existe uma pasta com esse nome.", "tileset_folder_delete_confirm": "Excluir a pasta {folder}? Os tilesets não serão excluídos.",
        "scan_subfolders": "Incluir subpastas", "batch_tileset_import": "Importar múltiplos tilesets",
        "tileset_asset_root_note": "Imagens externas serão copiadas para assets/tilesets.",
        "tileset_asset_root_required": "A pasta assets do projeto não está disponível.",
        "smart_terrain": "Smart Terrain", "terrain_family": "Família de terreno", "terrain_role": "Papel", "terrain_family_cards": "Famílias — passe o mouse para ver o conjunto 3 × 3",
        "terrain_family_floor_behavior": "Sem colisão", "terrain_family_wall_behavior": "Com colisão",
        "terrain_family_mixed_behavior": "Piso sem colisão; bordas com colisão",
        "terrain_seed": "Seed determinística", "floor": "Floor", "wall": "Wall", "room_brush": "Room / Area Brush",
        "terrain_active": "Terrain ativo: {family} / {role}", "terrain_active_walkable": "Terrain ativo: {family} — sem colisão", "terrain_active_solid": "Terrain ativo: {family} — com colisão", "no_terrain_family": "Nenhuma família semântica disponível",
        "semantic_editor": "Editor de Tile Semantic", "semantic_id": "ID semântico", "tile_name_id": "Nome / ID do tile", "family": "Família",
        "role": "Papel", "topology": "Topologia", "preferred_layer": "Camada preferida", "north": "Norte",
        "east": "Leste", "south": "Sul", "west": "Oeste", "flip_x_allowed": "Permitir flip X",
        "save_semantic": "Salvar semântica", "edit_tile_semantic": "Editar tile", "edit_tile_name_family": "Editar nome e família do tile...",
        "room_preview": "Pré-visualização da sala", "terrain_rectangle_preview": "Pré-visualização do retângulo de terreno", "erase_rectangle_preview": "Arraste para selecionar a área que será apagada",
        "semantic_saved": "Tile semantic salvo",
        "terrain_missing_candidate": "Nenhum tile semântico compatível foi encontrado",
        "configure_terrain_rule": "Gerenciar lógica Smart Terrain...", "terrain_rule_editor": "Gerenciador de Smart Terrain",
        "terrain_rule_family": "Família da regra", "terrain_rule_role": "Papel da regra", "terrain_rule_collision": "Colisão da família", "terrain_rule_slots": "Slots visuais 3 × 3",
        "terrain_rule_slots_hint": "Selecione uma posição da grade e clique no tile correspondente do atlas. A posição define a vizinhança usada pelo autotile.",
        "terrain_rule_click_atlas": "selecione um tile no atlas", "terrain_rule_save": "Salvar lógica", "terrain_rule_saved": "Lógica de Smart Terrain salva",
        "terrain_rule_existing": "Lógica existente", "terrain_rule_none": "Nova lógica", "terrain_rule_new": "Nova",
        "terrain_rule_delete": "Excluir lógica",
        "terrain_rule_delete_confirm": "Excluir a lógica {family} / {role}? As definições semânticas geradas serão removidas.",
        "terrain_rule_variants": "Variações do piso (até 9)",
        "terrain_rule_floor_hint": "Clique em um slot, escolha um tile no atlas e ajuste o peso. Exemplo: liso 8 + rachado 2 = aproximadamente 80% / 20%.",
        "terrain_rule_weight": "Frequência da variação", "terrain_rule_weight_suffix": " de peso",
        "terrain_rule_clear_slot": "Remover variação", "terrain_rule_variant_tooltip": "Tile #{index} — peso {weight}, aproximadamente {percent}%",
        "terrain_collision": "Colisão ao pintar", "preserve_collision": "Preservar colisão atual", "collision_on": "Ativar colisão", "collision_off": "Desativar colisão",
    },
    "en-US": {
        "app": "Dungeon Underworld — Content Studio", "map": "Map", "content": "Content",
        "maps_mode": "Maps", "content_mode": "Content", "maps": "Maps", "layers": "Layers", "tiles": "Tiles", "entities": "Entities", "spritesheets_animations": "Spritesheet / Animation", "inspector": "Inspector",
        "diagnostics": "Diagnostics", "new_project": "New Project", "open": "Open", "save": "Save",
        "save_as": "Save As", "save_all": "Save All", "validate": "Validate Workspace",
        "export": "Export DMAP", "playtest": "Playtest", "undo": "Undo", "redo": "Redo", "grid": "Grid",
        "select": "Select", "selection_deleted": "Selection deleted", "pencil": "Pencil", "erase": "Erase", "rectangle": "Rectangle",
        "fill": "Fill", "collision": "Collision", "entity": "Entity", "region": "Region",
        "search": "Search", "project": "Project", "builtin": "Engine / Builtin", "create": "Create",
        "delete": "Delete", "duplicate": "Duplicate", "add": "Add", "remove": "Remove",
        "rename": "Rename", "entry_map": "Entry Map", "untitled": "Untitled", "no_selection": "No selection",
        "map_create": "Create map", "map_edit_properties": "Map properties", "map_name_id": "Name / Map ID",
        "map_width_tiles": "Width (tiles)", "map_height_tiles": "Height (tiles)", "map_create_player_spawn": "Create initial Player Spawn",
        "map_folder": "Folder", "map_no_folder": "No folder",
        "map_new": "New map", "map_import": "Import UMAP", "map_remove": "Remove map", "map_set_entry": "Set as entry", "map_edit_properties_action": "Edit map properties...",
        "map_resize_hint": "When resizing, tiles and collision in the upper-left area are preserved.", "map_id_required": "Enter the name / Map ID.",
        "player_start_moved": "Player Start moved",
        "invalid": "Invalid",
        "file": "File", "edit": "Edit", "view": "View", "tools": "Tools",
        "new_content": "New Content Workspace", "open_project": "Open Project...",
        "open_content": "Open Content", "quit": "Exit", "frame": "Frame Map",
        "language": "Language", "definitions": "Definitions", "assets": "Assets",
        "semantics_stamps": "Semantics / Stamps", "map_elements": "Map Elements", "scenes": "Scenes", "rules_links": "Rules / Links",
        "tools_select": "Select", "tools_pencil": "Pencil", "tools_erase": "Erase",
        "tools_rectangle": "Rectangle", "tools_fill": "Fill", "tools_eyedropper": "Pick Tile",
        "tools_tile_selection": "Select Tiles", "tools_collision": "Collision +",
        "tools_collision_erase": "Collision -", "tools_collision_rectangle": "Collision Rect +",
        "tools_collision_rectangle_erase": "Collision Rect -", "tools_collision_fill": "Collision Fill +",
        "tools_collision_fill_erase": "Collision Fill -", "tools_entity": "Entity",
        "tools_spawn": "Player Spawn", "tools_link": "Map Link", "tools_region": "Region",
        "tools_stamp": "Stamp", "tools_pan": "Pan", "ready": "Ready",
        "snap": "Snap", "overlays": "Overlays", "playtest_toolbar": "Playtest",
        "player_spawn": "Player Spawn", "map_transition": "Map Transition", "region_element": "Region / Trigger",
        "map_elements_hint": "Drag an element to the map", "tileset_import": "Import Tileset", "import_tileset": "Import Tileset...",
        "browse": "Browse", "source_image": "Source image", "tileset_id": "Tileset ID",
        "display_name": "Display name", "tile_width": "Tile width", "tile_height": "Tile height",
        "spacing": "Spacing", "margin": "Margin", "copy_to_workspace": "Copy to workspace",
        "no_image": "No image", "image_unavailable": "Image unavailable", "invalid_image": "Invalid image",
        "grid_summary": "{width} × {height} px — {columns} × {rows} frames ({frames} total)", "grid_unused_edge": "Edge outside frames: {width} px on the right and {height} px below. This area will not be imported.",
        "frames_preview": "Frame division preview", "frame_preview_help": "Each thin blue line marks only the cut where the next frame column or row begins. The line is only a preview guide and does not alter the imported image.", "frame_bounds": "Example: frame 0, at the top left, uses X {left} through {right} and Y {top} through {bottom}, totaling {width} × {height} px.",
        "spritesheet_import": "Import spritesheet...", "image_id": "Image ID", "animation_id": "Animation ID", "frame_width": "Frame width", "frame_height": "Frame height", "frame_duration": "Duration per frame (ticks)", "animation_preview": "Animation result", "play_animation": "Play", "pause_animation": "Pause", "no_animations": "No imported animations", "animation_imported": "Spritesheet and animation imported", "edit_animation_frames": "Edit frames...", "edit_spritesheet_import": "Edit import...", "animation_frame": "Frame", "frame_offset_x": "X offset", "frame_offset_y": "Y offset", "center_current_frame": "Center this frame", "center_all_frames": "Center all", "reset_current_frame": "Reset this frame", "reset_all_frames": "Reset all", "frame_alignment_help": "Drag the image or use the arrows to move the frame in 1-pixel steps. The blue line shows the original frame area and the yellow cross shows its center. The original PNG will not be changed.", "animation_frames_updated": "Frame alignment updated", "spritesheet_import_updated": "Import settings updated",
        "tilesets": "Tilesets", "search_tilesets": "Search tilesets", "add_files": "Add Files...",
        "add_folder": "Import Folder...", "new_tileset_folder": "New Folder...", "reimport": "Reimport", "reimported": "Tileset reimported",
        "conflict": "Conflict", "skip": "Skip", "change_id": "Change ID", "incompatible": "incompatible",
        "tile_size": "Tile size", "default_tile_size": "Default tile size", "apply_to_all": "Apply to all", "tileset_grid": "Resulting grid",
        "manage_tileset": "Manage tileset...", "tileset_properties_saved": "Tileset properties updated",
        "tileset_folder": "Tileset folder", "tileset_no_folder": "No folder", "tileset_folder_memberships": "Organization folders", "tileset_folder_memberships_hint": "A tileset can belong to more than one folder.", "add_to_tileset_folder": "Add to folder", "remove_from_tileset_folder": "Remove from this folder", "rename_tileset_folder": "Rename folder...", "delete_tileset_folder": "Delete folder", "tileset_folder_name": "Folder name", "tileset_folder_exists": "A folder with that name already exists.", "tileset_folder_delete_confirm": "Delete folder {folder}? Its tilesets will not be deleted.",
        "scan_subfolders": "Include subfolders", "batch_tileset_import": "Import Multiple Tilesets",
        "tileset_asset_root_note": "External images will be copied into assets/tilesets.",
        "tileset_asset_root_required": "The project assets directory is unavailable.",
        "smart_terrain": "Smart Terrain", "terrain_family": "Terrain family", "terrain_role": "Role", "terrain_family_cards": "Families — hover to preview the 3 × 3 set",
        "terrain_family_floor_behavior": "No collision", "terrain_family_wall_behavior": "Collision enabled",
        "terrain_family_mixed_behavior": "Collision-free floor; colliding borders",
        "terrain_seed": "Deterministic seed", "floor": "Floor", "wall": "Wall", "room_brush": "Room / Area Brush",
        "terrain_active": "Terrain active: {family} / {role}", "terrain_active_walkable": "Active terrain: {family} — no collision", "terrain_active_solid": "Active terrain: {family} — with collision", "no_terrain_family": "No semantic family available",
        "semantic_editor": "Tile Semantic Editor", "semantic_id": "Semantic ID", "tile_name_id": "Tile name / ID", "family": "Family",
        "role": "Role", "topology": "Topology", "preferred_layer": "Preferred layer", "north": "North",
        "east": "East", "south": "South", "west": "West", "flip_x_allowed": "Allow X flip",
        "save_semantic": "Save semantic", "edit_tile_semantic": "Edit Tile", "edit_tile_name_family": "Edit tile name and family...",
        "room_preview": "Room preview", "terrain_rectangle_preview": "Terrain rectangle preview", "erase_rectangle_preview": "Drag to select the area to erase",
        "semantic_saved": "Tile semantic saved",
        "terrain_missing_candidate": "No compatible semantic tile was found",
        "configure_terrain_rule": "Manage Smart Terrain logic...", "terrain_rule_editor": "Smart Terrain Manager",
        "terrain_rule_family": "Rule family", "terrain_rule_role": "Rule role", "terrain_rule_collision": "Family collision", "terrain_rule_slots": "3 × 3 visual slots",
        "terrain_rule_slots_hint": "Select a grid position and click the corresponding atlas tile. The position defines the neighbourhood used by autotiling.",
        "terrain_rule_click_atlas": "select a tile in the atlas", "terrain_rule_save": "Save logic", "terrain_rule_saved": "Smart Terrain logic saved",
        "terrain_rule_existing": "Existing logic", "terrain_rule_none": "New logic", "terrain_rule_new": "New",
        "terrain_rule_delete": "Delete logic",
        "terrain_rule_delete_confirm": "Delete the {family} / {role} logic? Its generated semantic definitions will be removed.",
        "terrain_rule_variants": "Floor variations (up to 9)",
        "terrain_rule_floor_hint": "Click a slot, choose a tile in the atlas, and adjust its weight. Example: smooth 8 + cracked 2 = approximately 80% / 20%.",
        "terrain_rule_weight": "Variation frequency", "terrain_rule_weight_suffix": " weight",
        "terrain_rule_clear_slot": "Remove variation", "terrain_rule_variant_tooltip": "Tile #{index} — weight {weight}, approximately {percent}%",
        "terrain_collision": "Collision while painting", "preserve_collision": "Preserve current collision", "collision_on": "Enable collision", "collision_off": "Disable collision",
    },
}


class Translator:
    def __init__(self, language: str = "pt-BR") -> None:
        self.language = language if language in TRANSLATIONS else "pt-BR"

    def set_language(self, language: str) -> None:
        if language not in TRANSLATIONS:
            raise ValueError(language)
        self.language = language

    def __call__(self, key: str, **values: object) -> str:
        text = TRANSLATIONS[self.language].get(key, key)
        return text.format(**values) if values else text
