from __future__ import annotations


TRANSLATIONS = {
    "pt-BR": {
        "app": "Dungeon Underworld — Content Studio",
        "map": "Mapa", "content": "Conteúdo", "maps": "Mapas", "layers": "Camadas",
        "entities": "Entidades", "inspector": "Inspetor", "diagnostics": "Diagnósticos",
        "new_project": "Novo Projeto", "open": "Abrir", "save": "Salvar", "save_as": "Salvar Como",
        "save_all": "Salvar Tudo", "validate": "Validar Workspace", "export": "Exportar DMAP",
        "playtest": "Playtest", "undo": "Desfazer", "redo": "Refazer", "grid": "Grade",
        "select": "Selecionar", "pencil": "Lápis", "erase": "Apagar", "rectangle": "Retângulo",
        "fill": "Preencher", "collision": "Colisão", "entity": "Entidade", "region": "Região",
        "search": "Procurar", "project": "Projeto", "builtin": "Engine / Builtin",
        "create": "Criar", "delete": "Excluir", "duplicate": "Duplicar", "add": "Adicionar",
        "remove": "Remover", "rename": "Renomear", "entry_map": "Mapa de Entrada",
        "untitled": "Sem título", "no_selection": "Nenhuma seleção", "invalid": "Inválido",
        "file": "Arquivo", "edit": "Editar", "view": "Exibir", "tools": "Ferramentas",
        "new_content": "Novo Workspace de Conteúdo", "open_project": "Abrir Projeto...",
        "open_content": "Abrir Conteúdo", "quit": "Sair", "frame": "Enquadrar Mapa",
        "language": "Idioma", "definitions": "Definições", "assets": "Assets",
        "semantics_stamps": "Semântica / Stamps", "map_elements": "Elementos do Mapa", "scenes": "Cenas", "rules_links": "Regras / Links",
        "tools_select": "Selecionar", "tools_pencil": "Lápis", "tools_erase": "Apagar",
        "tools_rectangle": "Retângulo", "tools_fill": "Preencher", "tools_eyedropper": "Escolher Tile",
        "tools_tile_selection": "Selecionar Tiles", "tools_collision": "Colisão +",
        "tools_collision_erase": "Colisão -", "tools_collision_rectangle": "Colisão Ret +",
        "tools_collision_rectangle_erase": "Colisão Ret -", "tools_collision_fill": "Colisão Fill +",
        "tools_collision_fill_erase": "Colisão Fill -", "tools_entity": "Entidade",
        "tools_spawn": "Player Spawn", "tools_link": "Link de Mapa", "tools_region": "Região",
        "tools_stamp": "Stamp", "tools_pan": "Pan", "ready": "Pronto",
        "snap": "Snap", "overlays": "Sobreposições", "playtest_toolbar": "Playtest",
        "player_spawn": "Player Spawn", "map_transition": "Transição de Mapa", "region_element": "Região / Trigger",
        "map_elements_hint": "Arraste um elemento para o mapa", "tileset_import": "Importar Tileset", "import_tileset": "Importar Tileset...",
        "browse": "Procurar", "source_image": "Imagem fonte", "tileset_id": "ID do Tileset",
        "display_name": "Nome exibido", "tile_width": "Largura do tile", "tile_height": "Altura do tile",
        "spacing": "Espaçamento", "margin": "Margem", "copy_to_workspace": "Copiar para o workspace",
        "no_image": "Nenhuma imagem", "image_unavailable": "Imagem indisponível", "invalid_image": "Imagem inválida",
        "grid_summary": "{width} × {height} px — {columns} × {rows} tiles",
        "tilesets": "Tilesets", "search_tilesets": "Procurar tilesets", "add_files": "Adicionar arquivos...",
        "add_folder": "Adicionar pasta...", "reimport": "Reimportar", "reimported": "Tileset reimportado",
        "conflict": "Conflito", "skip": "Ignorar", "change_id": "Mudar ID", "incompatible": "incompatível",
        "tile_size": "Tamanho do tile", "default_tile_size": "Tamanho padrão", "apply_to_all": "Aplicar a todos",
        "scan_subfolders": "Incluir subpastas", "batch_tileset_import": "Importar múltiplos tilesets",
        "tileset_asset_root_note": "Imagens de tileset devem estar dentro do Asset Root configurado.",
        "tileset_asset_root_required": "Imagens de tileset devem estar dentro do Asset Root configurado.",
        "smart_terrain": "Smart Terrain", "terrain_family": "Família de terreno", "terrain_role": "Papel",
        "terrain_seed": "Seed determinística", "floor": "Floor", "wall": "Wall", "room_brush": "Room / Area Brush",
        "terrain_active": "Terrain ativo: {family} / {role}", "no_terrain_family": "Nenhuma família semântica disponível",
        "semantic_editor": "Editor de Tile Semantic", "semantic_id": "ID semântico", "family": "Família",
        "role": "Papel", "topology": "Topologia", "preferred_layer": "Camada preferida", "north": "Norte",
        "east": "Leste", "south": "Sul", "west": "Oeste", "flip_x_allowed": "Permitir flip X",
        "save_semantic": "Salvar semântica",
        "room_preview": "Pré-visualização da sala", "terrain_rectangle_preview": "Pré-visualização do retângulo de terreno",
        "semantic_saved": "Tile semantic salvo",
        "terrain_missing_candidate": "Nenhum tile semântico compatível foi encontrado",
        "configure_terrain_rule": "Configurar lógica de Smart Terrain...", "terrain_rule_editor": "Lógica de Smart Terrain",
        "terrain_rule_family": "Família da regra", "terrain_rule_role": "Papel da regra", "terrain_rule_slots": "Slots visuais 3 × 3",
        "terrain_rule_slots_hint": "Selecione uma posição da grade e clique no tile correspondente do atlas. A posição define a vizinhança usada pelo autotile.",
        "terrain_rule_click_atlas": "selecione um tile no atlas", "terrain_rule_save": "Salvar lógica", "terrain_rule_saved": "Lógica de Smart Terrain salva",
        "terrain_rule_existing": "Lógica existente", "terrain_rule_none": "Nova lógica", "terrain_rule_new": "Nova",
        "terrain_rule_delete": "Excluir lógica",
        "terrain_rule_delete_confirm": "Excluir a lógica {family} / {role}? As definições semânticas geradas serão removidas.",
        "terrain_collision": "Colisão ao pintar", "preserve_collision": "Preservar colisão atual", "collision_on": "Ativar colisão", "collision_off": "Desativar colisão",
    },
    "en-US": {
        "app": "Dungeon Underworld — Content Studio", "map": "Map", "content": "Content",
        "maps": "Maps", "layers": "Layers", "entities": "Entities", "inspector": "Inspector",
        "diagnostics": "Diagnostics", "new_project": "New Project", "open": "Open", "save": "Save",
        "save_as": "Save As", "save_all": "Save All", "validate": "Validate Workspace",
        "export": "Export DMAP", "playtest": "Playtest", "undo": "Undo", "redo": "Redo", "grid": "Grid",
        "select": "Select", "pencil": "Pencil", "erase": "Erase", "rectangle": "Rectangle",
        "fill": "Fill", "collision": "Collision", "entity": "Entity", "region": "Region",
        "search": "Search", "project": "Project", "builtin": "Engine / Builtin", "create": "Create",
        "delete": "Delete", "duplicate": "Duplicate", "add": "Add", "remove": "Remove",
        "rename": "Rename", "entry_map": "Entry Map", "untitled": "Untitled", "no_selection": "No selection",
        "invalid": "Invalid",
        "file": "File", "edit": "Edit", "view": "View", "tools": "Tools",
        "new_content": "New Content Workspace", "open_project": "Open Project...",
        "open_content": "Open Content", "quit": "Exit", "frame": "Frame Map",
        "language": "Language", "definitions": "Definitions", "assets": "Assets",
        "semantics_stamps": "Semantics / Stamps", "map_elements": "Map Elements", "scenes": "Scenes", "rules_links": "Rules / Links",
        "tools_select": "Select", "tools_pencil": "Pencil", "tools_erase": "Erase",
        "tools_rectangle": "Rectangle", "tools_fill": "Fill", "tools_eyedropper": "Pick Tile",
        "tools_tile_selection": "Select Tiles", "tools_collision": "Collision +",
        "tools_collision_erase": "Collision -", "tools_collision_rectangle": "Collision Rect +",
        "tools_collision_rectangle_erase": "Collision Rect -", "tools_collision_fill": "Collision Fill +",
        "tools_collision_fill_erase": "Collision Fill -", "tools_entity": "Entity",
        "tools_spawn": "Player Spawn", "tools_link": "Map Link", "tools_region": "Region",
        "tools_stamp": "Stamp", "tools_pan": "Pan", "ready": "Ready",
        "snap": "Snap", "overlays": "Overlays", "playtest_toolbar": "Playtest",
        "player_spawn": "Player Spawn", "map_transition": "Map Transition", "region_element": "Region / Trigger",
        "map_elements_hint": "Drag an element to the map", "tileset_import": "Import Tileset", "import_tileset": "Import Tileset...",
        "browse": "Browse", "source_image": "Source image", "tileset_id": "Tileset ID",
        "display_name": "Display name", "tile_width": "Tile width", "tile_height": "Tile height",
        "spacing": "Spacing", "margin": "Margin", "copy_to_workspace": "Copy to workspace",
        "no_image": "No image", "image_unavailable": "Image unavailable", "invalid_image": "Invalid image",
        "grid_summary": "{width} × {height} px — {columns} × {rows} tiles",
        "tilesets": "Tilesets", "search_tilesets": "Search tilesets", "add_files": "Add Files...",
        "add_folder": "Add Folder...", "reimport": "Reimport", "reimported": "Tileset reimported",
        "conflict": "Conflict", "skip": "Skip", "change_id": "Change ID", "incompatible": "incompatible",
        "tile_size": "Tile size", "default_tile_size": "Default tile size", "apply_to_all": "Apply to all",
        "scan_subfolders": "Include subfolders", "batch_tileset_import": "Import Multiple Tilesets",
        "tileset_asset_root_note": "Tileset images must be inside the configured Asset Root.",
        "tileset_asset_root_required": "Tileset images must be inside the configured Asset Root.",
        "smart_terrain": "Smart Terrain", "terrain_family": "Terrain family", "terrain_role": "Role",
        "terrain_seed": "Deterministic seed", "floor": "Floor", "wall": "Wall", "room_brush": "Room / Area Brush",
        "terrain_active": "Terrain active: {family} / {role}", "no_terrain_family": "No semantic family available",
        "semantic_editor": "Tile Semantic Editor", "semantic_id": "Semantic ID", "family": "Family",
        "role": "Role", "topology": "Topology", "preferred_layer": "Preferred layer", "north": "North",
        "east": "East", "south": "South", "west": "West", "flip_x_allowed": "Allow X flip",
        "save_semantic": "Save semantic",
        "room_preview": "Room preview", "terrain_rectangle_preview": "Terrain rectangle preview",
        "semantic_saved": "Tile semantic saved",
        "terrain_missing_candidate": "No compatible semantic tile was found",
        "configure_terrain_rule": "Configure Smart Terrain logic...", "terrain_rule_editor": "Smart Terrain Logic",
        "terrain_rule_family": "Rule family", "terrain_rule_role": "Rule role", "terrain_rule_slots": "3 × 3 visual slots",
        "terrain_rule_slots_hint": "Select a grid position and click the corresponding atlas tile. The position defines the neighbourhood used by autotiling.",
        "terrain_rule_click_atlas": "select a tile in the atlas", "terrain_rule_save": "Save logic", "terrain_rule_saved": "Smart Terrain logic saved",
        "terrain_rule_existing": "Existing logic", "terrain_rule_none": "New logic", "terrain_rule_new": "New",
        "terrain_rule_delete": "Delete logic",
        "terrain_rule_delete_confirm": "Delete the {family} / {role} logic? Its generated semantic definitions will be removed.",
        "terrain_collision": "Collision while painting", "preserve_collision": "Preserve current collision", "collision_on": "Enable collision", "collision_off": "Disable collision",
    },
}


class Translator:
    def __init__(self, language: str = "pt-BR") -> None:
        self.language = language if language in TRANSLATIONS else "pt-BR"

    def set_language(self, language: str) -> None:
        if language not in TRANSLATIONS:
            raise ValueError(language)
        self.language = language

    def __call__(self, key: str, **values: object) -> str:
        text = TRANSLATIONS[self.language].get(key, key)
        return text.format(**values) if values else text
